<a href="https://colab.research.google.com/github/Vatsal-Patel-09/Machine_Learning_101/blob/main/LAB_3-nppy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercises

### 1.Basic Array Creation & Manipulation
- Create a 1D array of numbers from 1 to 20.
- Create a 3×4 matrix of ones and reshape it to 4×3.
- Create a 5×5 identity matrix.
- Generate 15 equally spaced numbers between 5 and 50.
- Generate a 4×4 matrix of random integers between 1 and 100.

In [31]:
import numpy as np

In [32]:
#Create a 1D array of numbers from 1 to 20.
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [33]:
#Create a 3×4 matrix of ones and reshape it to 4×3.
arr = np.ones((3,4))
print(arr)
arr = arr.reshape(4,3)
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
# Create a 5×5 identity matrix.
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
#Generate 15 equally spaced numbers between 5 and 50.
arr = np.linspace(5,50,15,)
print(arr)

[ 5.          8.21428571 11.42857143 14.64285714 17.85714286 21.07142857
 24.28571429 27.5        30.71428571 33.92857143 37.14285714 40.35714286
 43.57142857 46.78571429 50.        ]


In [36]:
#Generate a 4×4 matrix of random integers between 1 and 100
arr = np.random.randint(1,101,(4,4))
print(arr)

[[10 19 13 67]
 [68 40 60 30]
 [69 58 10 49]
 [35 53 70 33]]


### 2.Indexing, Slicing, and Broadcasting
- Create a 3×3 matrix of random integers between 1 and 100.
- Extract: First row, Second column, Center element.
- Replace all values greater than 50 in a matrix with 999.
- Multiply a 1D array of size 5 (random integers between 1 to 10) by 10 using
broadcasting

In [37]:
#Create a 3×3 matrix of random integers between 1 and 100.
arr = np.random.randint(1,101,(3,3))
print(arr)

[[63 80 27]
 [75 35 69]
 [80 63 26]]


In [38]:
#Extract: First row, Second column, Center element.
print(arr[0])
print(arr[:,1:2])
print(arr[1,1])

[63 80 27]
[[80]
 [35]
 [63]]
35


In [39]:
#Replace all values greater than 50 in a matrix with 999.
arr[arr > 50] = 999
print(arr)

[[999 999  27]
 [999  35 999]
 [999 999  26]]


In [40]:
#Multiply a 1D array of size 5 (random integers between 1 to 10) by 10 using broadcasting
arr1 = np.random.randint(1,11,5)
print(arr1)
arr2 = 10
print(arr1*arr2)

[5 7 1 8 4]
[50 70 10 80 40]


### 3.Mathematical and Statistical Operations  
- Create a 3×3 matrix of random integers between 1 and 100
- Compute sum, mean, median, std, var, min, and max of the above array.
- Normalize a 1D array of size 5 (random integers between 1 to 10)  to scale values
between 0 and 1

In [41]:
#Create a 3×3 matrix of random integers between 1 and 100.
arr = np.random.randint(1,101,(3,3))
print(arr)

[[84 65 69]
 [39 43 99]
 [26 19 38]]


In [42]:
# Compute sum, mean, median, std, var, min, and max of the above array.
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

482
53.55555555555556
43.0
25.56086901283597
653.358024691358
19
99


In [43]:
#Normalize a 1D array of size 5 (random integers between 1 to 10) to scale values between 0 and 1
arr2 = np.random.randint(1,11,5)
print(arr2)
arr2 = (arr2 - np.min(arr2)) / (np.max(arr2) - np.min(arr2))
print(arr2)

[10  4  4  6  3]
[1.         0.14285714 0.14285714 0.42857143 0.        ]


### 4.NumPy Matrix Operations and Linear Algebra  
- Generate Following two NumPy matrix import numpy as np
      A = ([4, 2], [1, 3])
      B = ([2, 0], [1, 5])
- Find matrix multiplication of A and B.
- Find dot product of A and B.
- Find element wise addition/ subtraction/ multiplications/ division of A and B
- Transpose matrix A.
- Compute determinant of A.
- Compute inverse of A (if possible).
- Find eigenvalues and eigenvectors.
- Solve the system of equations:
      2x + y = 8  
      3x + 4y = 18


In [73]:
#Generate Following two NumPy matrix import numpy as np
A = np.array([[4, 2], [1, 3]])
B = np.array([[2, 1], [1, 5]])
# print(A)
# print(B)
#Find matrix multiplication of A and B.
print("Matrix Multiplication:")
print(A*B)

# Find dot product of A and B.
print("\nDot Product:")
print(np.dot(A, B))

Matrix Multiplication:
[[ 8  2]
 [ 1 15]]

Dot Product:
[[10 14]
 [ 5 16]]


In [74]:
#Find element wise addition/ subtraction/ multiplications/ division of A and B
print("\nElement Wise Addition:")
print(A+B)
print("\nElement Wise Subtraction:")
print(A-B)
print("\nElement Wise Multiplication:")
print(A*B)
print("\nElement Wise Division:")
print(A/B)


Element Wise Addition:
[[6 3]
 [2 8]]

Element Wise Subtraction:
[[ 2  1]
 [ 0 -2]]

Element Wise Multiplication:
[[ 8  2]
 [ 1 15]]

Element Wise Division:
[[2.  2. ]
 [1.  0.6]]


In [75]:
#Transpose matrix A.
print(A.T)

[[4 1]
 [2 3]]


In [76]:
#Compute determinant of A
print(np.linalg.det(A))

10.000000000000002


In [78]:
#Compute inverse of A (if possible)
print(np.linalg.inv(A))

[[ 0.3 -0.2]
 [-0.1  0.4]]


In [81]:
#Find eigenvalues and eigenvectors.
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [87]:
# Solve the system of equations: 2x + y = 8, 3x + 4y = 18

A = np.array([[2, 1], [3, 4]])

B = np.array([8, 18])

solution = np.linalg.solve(A, B)

print("Solution (x, y):", solution)

Solution (x, y): [2.8 2.4]


# Pandas Exercises

### 1.Series & DataFrame Basics
- Given the following list of marks: [78, 85, 92, 70, 66]
- Create a Pandas Series and assign the following student names as indices: ['Amit', 'Bhavna', 'Chetan', 'Divya', 'Esha']
- Display the Series.


In [45]:
import pandas as pd

In [46]:
marks = [78, 85, 92, 70, 66]
names = ['Amit', 'Bhavna', 'Chetan', 'Divya', 'Esha']

In [47]:
arr = pd.Series(marks, index = names)
print(arr)

Amit      78
Bhavna    85
Chetan    92
Divya     70
Esha      66
dtype: int64


Using the following dictionary:

data = {
'Name': ['Amit', 'Bhavna', 'Chetan', 'Divya', 'Esha'],
'Gender': ['Male', 'Female', 'Male', 'Female', 'Female'],
'Math': [78, 85, 92, 70, 66],
'Science': [88, 79, 95, 72, 60]
}

Create a Pandas DataFrame and display:
- The full DataFrame
- The column names
- The shape of the DataFrame

In [48]:
data = {
'Name': ['Amit', 'Bhavna', 'Chetan', 'Divya', 'Esha'],
'Gender': ['Male', 'Female', 'Male', 'Female', 'Female'],
'Math': [78, 85, 92, 70, 66],
'Science': [88, 79, 95, 72, 60]
}

In [49]:
df = pd.DataFrame(data)
print(df)

     Name  Gender  Math  Science
0    Amit    Male    78       88
1  Bhavna  Female    85       79
2  Chetan    Male    92       95
3   Divya  Female    70       72
4    Esha  Female    66       60


In [50]:
print(df.columns)
print(df.shape)

Index(['Name', 'Gender', 'Math', 'Science'], dtype='object')
(5, 4)


### 2.Data Exploration
- Load the dataset from this url "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
- Assign names of columns:

["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style", "drive-wheels","engine-location","wheel-base","length","width","height","curb-weight","engine-type","num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
"peak-rpm","city-mpg","highway-mpg","price"]
- Display .shape, .columns, .info(), and .describe().
- Display only ","width","height","curb-weight","engine-type" columns.
- Display car details which have num-of-doors = four

In [51]:
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
column_names = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style", "drive-wheels","engine-location","wheel-base","length","width","height","curb-weight","engine-type","num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
"peak-rpm","city-mpg","highway-mpg","price"]

In [52]:
df_data = pd.read_csv(data_url, names = column_names, delimiter= ",", na_values= "?")

In [53]:
print(df_data.head(5))

   symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std   
1          3                NaN  alfa-romero       gas        std   
2          1                NaN  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68       

In [54]:
print(df_data.shape)
print(df_data.columns)
print(df_data.info())
print(df_data.describe())

(205, 26)
Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  164 non-null    float64
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       203 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 no

In [55]:
print(df_data.head(5)[["width","height","curb-weight","engine-type"]])

   width  height  curb-weight engine-type
0   64.1    48.8         2548        dohc
1   64.1    48.8         2548        dohc
2   65.5    52.4         2823        ohcv
3   66.2    54.3         2337         ohc
4   66.4    54.3         2824         ohc


In [56]:
print(df_data[df_data["num-of-doors"] == "four"].head(5))

   symboling  normalized-losses  make fuel-type aspiration num-of-doors  \
3          2              164.0  audi       gas        std         four   
4          2              164.0  audi       gas        std         four   
6          1              158.0  audi       gas        std         four   
7          1                NaN  audi       gas        std         four   
8          1              158.0  audi       gas      turbo         four   

  body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
3      sedan          fwd           front        99.8  ...          109   
4      sedan          4wd           front        99.4  ...          136   
6      sedan          fwd           front       105.8  ...          136   
7      wagon          fwd           front       105.8  ...          136   
8      sedan          fwd           front       105.8  ...          131   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
3         mpfi  3.

### 3.Missing values handling  
- Missing value is represented by ‘?’ in this dataset. Replace it with NULL.
- Check how many missing values are there in each attribute.
- Replace missing values of "normalized-losses", "stroke", "bore", "horsepower" with
mean.
- Drop all the rows which has missing value in attribute “price”.**bold text**
- Replace missing values of “num-of-doors” with mode.
- Replace all other missing values with median.

In [57]:
#Missing value is represented by ‘?’ in this dataset. Replace it with NULL.
print(df_data.head(7).fillna(value = "NULL"))

   symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3              NULL  alfa-romero       gas        std          two   
1          3              NULL  alfa-romero       gas        std          two   
2          1              NULL  alfa-romero       gas        std          two   
3          2             164.0         audi       gas        std         four   
4          2             164.0         audi       gas        std         four   
5          2              NULL         audi       gas        std          two   
6          1             158.0         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front

In [58]:
#Check how many missing values are there in each attribute.
print(df_data.isnull().sum())

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64


In [59]:
#Replace missing values of "normalized-losses", "stroke", "bore", "horsepower" with mean.
df_data["normalized-losses"] = df_data["normalized-losses"].fillna(df_data["normalized-losses"].mean())
df_data["stroke"] = df_data["stroke"].fillna(df_data["stroke"].mean())
df_data["bore"] = df_data["bore"].fillna(df_data["bore"].mean())
df_data["horsepower"] = df_data["horsepower"].fillna(df_data["horsepower"].mean())

print(df_data.head(5))


   symboling  normalized-losses         make fuel-type aspiration  \
0          3              122.0  alfa-romero       gas        std   
1          3              122.0  alfa-romero       gas        std   
2          1              122.0  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68       

In [60]:
#Drop all the rows which has missing value in attribute “price”

print(df_data[df_data["price"].isnull()])
df_data = df_data.dropna(subset=['price'])

     symboling  normalized-losses     make fuel-type aspiration num-of-doors  \
9            0              122.0     audi       gas      turbo          two   
44           1              122.0    isuzu       gas        std          two   
45           0              122.0    isuzu       gas        std         four   
129          1              122.0  porsche       gas        std          two   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
9    hatchback          4wd           front        99.5  ...          131   
44       sedan          fwd           front        94.5  ...           90   
45       sedan          fwd           front        94.5  ...           90   
129  hatchback          rwd           front        98.4  ...          203   

     fuel-system  bore  stroke compression-ratio horsepower  peak-rpm  \
9           mpfi  3.13    3.40               7.0      160.0    5500.0   
44          2bbl  3.03    3.11               9.6       70.0    5400

In [61]:
# Replace missing values of “num-of-doors” with mode.
df_data["num-of-doors"] = df_data["num-of-doors"].fillna(df_data["num-of-doors"].mode()[0])
print(df_data.head(5))

   symboling  normalized-losses         make fuel-type aspiration  \
0          3              122.0  alfa-romero       gas        std   
1          3              122.0  alfa-romero       gas        std   
2          1              122.0  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68       

/tmp/ipython-input-61-1088669806.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_data["num-of-doors"] = df_data["num-of-doors"].fillna(df_data["num-of-doors"].mode()[0])


In [62]:
# Replace all other missing values with median.
# peak-rpm has 2 missing values
df_data["peak-rpm"] = df_data["peak-rpm"].fillna(df_data["peak-rpm"].median())
#no missing values
print(df_data.isnull().sum())

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64


/tmp/ipython-input-62-1935293583.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_data["peak-rpm"] = df_data["peak-rpm"].fillna(df_data["peak-rpm"].median())


### 4.Grouping, Sorting, and Aggregation  
- Group by “Fuel-type” and compute average price.
- In our dataset, the fuel consumption columns "city-mpg" and "highway-mpg" are
represented by mpg (miles per gallon) unit.

    Assume we are developing an application in
    a country that accept the fuel consumption with L/100km standard
We will need to apply data transformation to transform mpg into L/100km?
      The formula for unit conversion is
      L/100km = 235 / mpg
-Sort the DataFrame based on “price” in descending order.

In [63]:
# Group by “Fuel-type” and compute average price.
fuel_price = df_data.groupby('fuel-type')['price'].mean()
print(fuel_price)

fuel-type
diesel    15838.15000
gas       12916.40884
Name: price, dtype: float64


In [64]:
#convert mpg (miles per gallon) to  L/100km standard for 2 rows "city-mpg" and "highway-mpg".
# conversion formula: L/100km = 235 / mpg

In [65]:
# Convert mpg to L/100km
df_data['city-L/100km'] = 235 / df_data['city-mpg']
df_data['highway-L/100km'] = 235 / df_data['highway-mpg']

# Display the first 5 rows with the new columns
print(df_data[['city-mpg', 'city-L/100km', 'highway-mpg', 'highway-L/100km']].head())

   city-mpg  city-L/100km  highway-mpg  highway-L/100km
0        21     11.190476           27         8.703704
1        21     11.190476           27         8.703704
2        19     12.368421           26         9.038462
3        24      9.791667           30         7.833333
4        18     13.055556           22        10.681818


In [66]:
#Sort the DataFrame based on “price” in descending order.

In [67]:
# Sort the DataFrame based on “price” in descending order.
df_data_sorted = df_data.sort_values(by='price', ascending=False)
print(df_data_sorted["price"].head(7))

74     45400.0
16     41315.0
73     40960.0
128    37028.0
17     36880.0
49     36000.0
48     35550.0
Name: price, dtype: float64
